---
apiVersion: v1
kind: ConfigMap
metadata:
  name: elasticsearch-client-config
  labels:
    app: elasticsearch
    role: client
data:
  elasticsearch.yml: |-
    cluster.name: ${CLUSTER_NAME}
    node.name: ${NODE_NAME}
    discovery.seed_hosts: ${NODE_LIST}
    cluster.initial_master_nodes: ${MASTER_NODES}
    network.host: 0.0.0.0
    node:
      master: false
      data: false
      ingest: true
    xpack.security.enabled: true
    xpack.monitoring.collection.enabled: true
    xpack.security.http.ssl.enabled: true
    xpack.security.transport.ssl.enabled: true
    xpack.security.http.ssl.key: certs/cert.key
    xpack.security.http.ssl.certificate: certs/cert.crt
    xpack.security.http.ssl.certificate_authorities: certs/chain.crt
    xpack.security.transport.ssl.key: certs/cert.key
    xpack.security.transport.ssl.certificate: certs/cert.crt
    xpack.security.transport.ssl.certificate_authorities: certs/chain.crt
    xpack.security.transport.ssl.verification_mode: certificate
---
