---
apiVersion: v1
kind: Service
metadata:
  name: kibana
  labels:
    app: kibana
spec:
  type: LoadBalancer
  ports:
  - port: 443
    name: webinterface
    targetPort: 5601
  selector:
    app: kibana
---
