---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kibana-config
  labels:
    app: kibana
data:
  kibana.yml: |-
    server.host: 0.0.0.0
    server.ssl.enabled: true
    server.ssl.certificate: /usr/share/kibana/config/certs/cert.crt
    server.ssl.key: /usr/share/kibana/config/certs/cert.key
    elasticsearch.hosts: ${ELASTICSEARCH_HOSTS}
    elasticsearch.username: ${ELASTICSEARCH_USER}
    elasticsearch.password: ${ELASTICSEARCH_PASSWORD}
    elasticsearch.ssl.certificateAuthorities: [ "/usr/share/kibana/config/certs/chain.crt" ]
    elasticsearch.ssl.verificationMode: none
---
